name: ci

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  autofarming:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto Farming
        run: |
          git config --local user.email "ghyghoo8@gmail.com"
          git config --local user.name "farmer@ghy"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "day day farming, more more money."
          git push
